### ISSUE TITLE
CT-Financial Dashboard

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebMApp1#15]
CT-Financial Dashboard

**Comment by 0340LalitGupta** [comment]
1. Separate App
==========
![image](https://user-images.githubusercontent.com/37236522/55002238-40430e00-4ffc-11e9-8eb9-7cb16870600e.png)
2. Output
======
![image](https://user-images.githubusercontent.com/37236522/55002652-01618800-4ffd-11e9-9025-c068f673315e.png)


![image](https://user-images.githubusercontent.com/37236522/55002547-d414da00-4ffc-11e9-9f31-74c764710df8.png)
3. Billing Info-Separate Page
==================
![image](https://user-images.githubusercontent.com/37236522/55002848-4e455e80-4ffd-11e9-9742-bc4764cd7aba.png)

**Comment by hariharan-isgec** [comment]
Change approved for production
